[package]
name = "snakegame"
version = "0.1.0"
authors = ["Abdirrahman Mohamed <abdirrahmang@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
piston_window = "0.113.0"
